/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Track title or topic shown on both sides
 */
export type Topic = string;
/**
 * Artist or short description
 */
export type Text = string;
/**
 * Cover artwork shown on the front of the card
 */
export type Image = string;
/**
 * Alt text for the cover; falls back to the asset's own alt text
 */
export type AlternativeText = string;
/**
 * URL of the audio file to play on the back (Storyblok CDN URL or an external preview link)
 */
export type PreviewURL = string;

/**
 * Flip card presenting a track: cover and topic on the front, audio player on the back
 */
export interface TrackTeaserBoxProps {
  topic?: Topic;
  text?: Text;
  image?: Image;
  alt?: AlternativeText;
  preview?: PreviewURL;
}
